### ISSUE TITLE
DatePicker ValueChanged return wrong date

### ISSUE THREAD

**Issue by roustan2** [SamProf/MatBlazor#164]
code:
 <MatDatePicker  ValueChanged="@OnChangeDate"></MatDatePicker>
  void OnChangeDate(DateTime ?D2)
    {

    }
returned date is selected date -1 day :-(
ex: select 10/08/2019 return 09/08/2019

**Comment by roustan2** [comment]
not a bug.
need convert date to locale

**Comment by kaanlab** [comment]
doesn't work:
```
<MatDatePicker@bind-Value="@PikDate"></MatDatePicker>

<p>date: @PikDate.Value.ToString("dd MMMM yyyy", CultureInfo.GetCultureInfo("en-US"))</p>

@code {
   public DateTime? PikDate { get; set; }
}
```

**Comment by SamProf** [comment]
I think that `.ToLocalTime()` should resolve this problem for all. And it's works in Server side Blazor, but I found that in Client Side Blazor this not works. So, problem is really exists.

So, fixing is in progress.

**Comment by iAmBipinPaul** [comment]
I had the same issue so I used this package , till it's gets fixed in mono (wasm).
https://github.com/jsakamoto/Toolbelt.Blazor.TimeZoneKit

https://github.com/aspnet/Blazor/issues/1166

**Comment by kaanlab** [comment]
In my case this package did not help.  I still have this bug.

**Comment by agonzalezm** [comment]
.ToLocalTime() doesnt work in server-side blazor, still shows UTC. is there anyway to convert utc times to user browser timezone in SSB?

**Comment by iAmBipinPaul** [comment]
@kaanlab 
> In my case this package did not help. I still have this bug.

This show work , needs to use to `ToLocalTime()`

example 
```csharp
DateTime.Now.ToLocalTime() // should return local time
```

**Comment by kaanlab** [comment]
@iAmBipinPaul  packege +.ToLocalTime() doesn't work in client-side blazor (webassembly)

**Comment by iAmBipinPaul** [comment]
Hi @kaanlab 
 It does work  in my case and my timezone is `Asia/Kathmandu`

in `startup.cs`
```csharp
 public void Configure(IComponentsApplicationBuilder app)
        {
            app.UseLocalTimeZone();
            app.AddComponent<App>("app");
        }
```
Then 
```csharp
DateTime.Now.ToLocalTime() // should return local time
```
It return local time.

Try changing your system time zone to some other timezone. May be, your timezone may not be supported by this package,
